spring:
  application:
    name: feign

server:
  port: 3001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

# \u516C\u7528\u914D\u7F6E
ribbon:
  ReadTimeout: 1500

# \u53EA\u9488\u5BF9\u4E00\u4E2A\u670D\u52A1\u8FDB\u884C\u914D\u7F6E
item-service:
  ribbon:
    MaxAutoRetries: 1              # \u9ED8\u8BA4 0
    MaxAutoRetriesNextServer: 2    # \u9ED8\u8BA4 1

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream







